<?xml version="1.0" encoding="utf-8"?>
<Database Name="ForgeDownloadManager" Class="ForgeLinksDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=ForgeDownloadManager;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SiteSqlServer" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ForgeLink" Member="ForgeLinks">
    <Type Name="ForgeLink">
      <Column Name="ForgeLinkId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ModuleId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Label" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FileId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ForgeTemplateId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="ForgeLinkTemplate_ForgeLink" Member="ForgeLinkTemplate" ThisKey="ForgeTemplateId" OtherKey="ForgeTemplateId" Type="ForgeLinkTemplate" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ForgeLinkTemplate" Member="ForgeLinkTemplates">
    <Type Name="ForgeLinkTemplate">
      <Column Name="ForgeTemplateId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ModuleId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Template" Type="System.String" DbType="NVarChar(500) NOT NULL" CanBeNull="false" />
      <Association Name="ForgeLinkTemplate_ForgeLink" Member="ForgeLinks" ThisKey="ForgeTemplateId" OtherKey="ForgeTemplateId" Type="ForgeLink" />
    </Type>
  </Table>
  <Table Name="dbo.ForgeLinkSettings" Member="ForgeLinkSettings">
    <Type Name="ForgeLinkSetting">
      <Column Name="ForgeSettingsId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ModuleId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProjectName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ReleaseId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Template" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="AltTemplate" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>